spring:
  application:
    name: swift-microgateway

  config:
    import:
      - "file:D:/config/client-secret.yml"
      - "file:D:/config/config.yml"
  security:
    user:
      name: admin   # Username
      password: admin123  # Password

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      routes:
        - id: swift-service
          uri: ${external.swift-uri}
          predicates:
            - Path=${external.swift-uri-path}
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestedTokens: 1 # Number of tokens consumed per request
                key-resolver: "#{@userKeyResolver}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
    beans:
      enabled: true


#application logging level
logging:
  level:
    root: info

